-- BTS Manager - Supabase PostgreSQL schema
-- Run this in Supabase Dashboard -> SQL Editor.
-- This script creates the shared BTS/MLL data model, RLS and audit logging.

create extension if not exists pgcrypto;

create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text, area text, type text, status text default 'Hoạt động',
  address text, latitude text, longitude text, owner_contact text,
  owner_phone text, technician text, phone text, note text,
  upe text, meter_code text, pole_type text, csht_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contracts (
  contract_id text primary key, station_code text, contract_no text,
  contract_type text, lessor text, address text, sign_date text,
  start_date text, end_date text, rent_amount text, payment_cycle text,
  contact_name text, contact_phone text, status text, file_name text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.equipment (
  equipment_id text primary key, station_code text, equipment_group text,
  vendor text, model text, serial_no text, part_no text, ip_address text,
  mac_address text, software_version text, location text, install_date text,
  status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.transmission (
  transmission_id text primary key, station_code text, link_type text,
  path_role text, device_a text, port_a text, device_b text, port_b text,
  media text, fiber_core text, sfp_a text, sfp_a_wavelength text,
  sfp_a_speed text, sfp_b text, sfp_b_wavelength text, sfp_b_speed text,
  vlan text, wan_ip text, lan_ip text, gateway text, network text,
  lacp text, main_backup text, provider text, status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.power (
  power_id text primary key, station_code text, power_vendor text,
  power_model text, capacity_a text, dc_voltage text, dc_load_a text,
  ac_voltage text, ac_load_a text, rectifier_count text,
  rectifier_working text, llvd1_v text, llvd2_v text, blvd_v text,
  controller_ip text, snmp text, modbus text, status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.batteries (
  battery_id text primary key, station_code text, battery_type text,
  vendor text, model text, serial_no text, voltage_v text,
  capacity_ah text, cell_count text, soc_percent text, soh_percent text,
  voltage_online text, current_a text, install_date text, status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.auxiliary (
  aux_id text primary key, station_code text, category text, vendor text,
  model text, serial_no text, specification text, quantity text,
  location text, install_date text, status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.maintenance (
  work_id text primary key, station_code text, area text, scope text,
  work_type text, work_date text, technician text, content text,
  condition_before text, result text, materials text, cost text,
  status text, note text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.mll_events (
  id bigint generated by default as identity primary key,
  month text, station_code text, dept text, cb_type text,
  g5 text, g3 text, g4 text, start_date text, start_time text,
  end_date text, end_time text, downtime_min double precision,
  handler text, error_code text, error_content text, resolution text,
  bsc_min double precision, layer_min double precision, csht_code text, csht_type text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.mll_bsc_summary (
  id bigint generated by default as identity primary key,
  dept text not null,
  month_no integer not null,
  value double precision,
  avg_6m double precision,
  updated_at timestamptz not null default now(),
  unique(dept, month_no)
);

create table if not exists public.mll_analysis_summary (
  range_key text primary key,
  from_month integer not null,
  to_month integer not null,
  cases integer not null default 0,
  total_downtime double precision not null default 0,
  avg_per_event double precision not null default 0,
  stations integer not null default 0,
  top_reason text,
  monthly_json jsonb not null default '[]'::jsonb,
  reason_json jsonb not null default '[]'::jsonb,
  service_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.kpi_targets (
  content text primary key,
  target text,
  actual text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table if exists public.kpi_targets add column if not exists actual text;

-- V85.60 MLL authoritative fields published by PC and consumed by Mobile.
alter table if exists public.mll_analysis_summary add column if not exists total_bsc double precision;
alter table if exists public.mll_analysis_summary add column if not exists total_layer double precision;
alter table if exists public.mll_analysis_summary add column if not exists bsc_avg double precision;
alter table if exists public.mll_analysis_summary add column if not exists bsc_target double precision;
alter table if exists public.mll_analysis_summary add column if not exists top_station_json jsonb not null default '[]'::jsonb;
alter table if exists public.mll_analysis_summary add column if not exists longest_json jsonb not null default '[]'::jsonb;
alter table if exists public.mll_analysis_summary add column if not exists insight text;

create index if not exists idx_stations_code on public.stations(code);
create index if not exists idx_stations_upe on public.stations(upe);
create index if not exists idx_stations_type on public.stations(type);
create index if not exists idx_stations_technician on public.stations(technician);
create index if not exists idx_contracts_station on public.contracts(station_code);
create index if not exists idx_equipment_station on public.equipment(station_code);
create index if not exists idx_transmission_station on public.transmission(station_code);
create index if not exists idx_power_station on public.power(station_code);
create index if not exists idx_batteries_station on public.batteries(station_code);
create index if not exists idx_auxiliary_station on public.auxiliary(station_code);
create index if not exists idx_maintenance_station on public.maintenance(station_code);
create index if not exists idx_mll_station on public.mll_events(station_code);
create index if not exists idx_mll_month on public.mll_events(month);
create index if not exists idx_mll_error on public.mll_events(error_code);
create index if not exists idx_mll_bsc_month on public.mll_bsc_summary(month_no);
create index if not exists idx_mll_analysis_range on public.mll_analysis_summary(from_month, to_month);
create index if not exists idx_kpi_content on public.kpi_targets(content);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  row_pk text,
  action text not null,
  changed_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null,
  old_data jsonb,
  new_data jsonb
);

create index if not exists idx_audit_table_time on public.audit_log(table_name, changed_at desc);

create or replace function public.bts_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.bts_audit_row()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  pk text;
begin
  if tg_op = 'DELETE' then
    pk := coalesce(to_jsonb(old)->>tg_argv[0], '');
    insert into public.audit_log(table_name,row_pk,action,changed_by,old_data)
    values (tg_table_name,pk,tg_op,auth.uid(),to_jsonb(old));
    return old;
  elsif tg_op = 'UPDATE' then
    pk := coalesce(to_jsonb(new)->>tg_argv[0], '');
    insert into public.audit_log(table_name,row_pk,action,changed_by,old_data,new_data)
    values (tg_table_name,pk,tg_op,auth.uid(),to_jsonb(old),to_jsonb(new));
    return new;
  else
    pk := coalesce(to_jsonb(new)->>tg_argv[0], '');
    insert into public.audit_log(table_name,row_pk,action,changed_by,new_data)
    values (tg_table_name,pk,tg_op,auth.uid(),to_jsonb(new));
    return new;
  end if;
end;
$$;

do $$
declare
  rec record;
begin
  for rec in
    select * from (values
      ('stations','code'),
      ('contracts','contract_id'),
      ('equipment','equipment_id'),
      ('transmission','transmission_id'),
      ('power','power_id'),
      ('batteries','battery_id'),
      ('auxiliary','aux_id'),
      ('maintenance','work_id'),
      ('mll_events','id'),
      ('mll_bsc_summary','id'),
      ('mll_analysis_summary','range_key'),
      ('kpi_targets','content')
    ) as x(table_name, pk_column)
  loop
    execute format('drop trigger if exists %I on public.%I', 'trg_'||rec.table_name||'_updated_at', rec.table_name);
    execute format('create trigger %I before update on public.%I for each row execute function public.bts_set_updated_at()', 'trg_'||rec.table_name||'_updated_at', rec.table_name);
    execute format('drop trigger if exists %I on public.%I', 'trg_'||rec.table_name||'_audit', rec.table_name);
    execute format('create trigger %I after insert or update or delete on public.%I for each row execute function public.bts_audit_row(%L)', 'trg_'||rec.table_name||'_audit', rec.table_name, rec.pk_column);
  end loop;
end $$;

-- Shared BTS Manager data: authenticated users can collaborate on the same dataset.
-- Anonymous/public requests are not allowed.
do $$
declare t text;
begin
  foreach t in array array['stations','contracts','equipment','transmission','power','batteries','auxiliary','maintenance','mll_events','mll_bsc_summary','mll_analysis_summary','kpi_targets'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated_select" on public.%I', t);
    execute format('drop policy if exists "authenticated_insert" on public.%I', t);
    execute format('drop policy if exists "authenticated_update" on public.%I', t);
    execute format('drop policy if exists "authenticated_delete" on public.%I', t);
    execute format('create policy "authenticated_select" on public.%I for select to authenticated using (true)', t);
    execute format('create policy "authenticated_insert" on public.%I for insert to authenticated with check (true)', t);
    execute format('create policy "authenticated_update" on public.%I for update to authenticated using (true) with check (true)', t);
    execute format('create policy "authenticated_delete" on public.%I for delete to authenticated using (true)', t);
  end loop;
end $$;

alter table public.audit_log enable row level security;
drop policy if exists "authenticated_audit_select" on public.audit_log;
create policy "authenticated_audit_select" on public.audit_log for select to authenticated using (true);

-- API privileges are intentionally limited to authenticated users for these shared tables.
grant select, insert, update, delete on public.stations, public.contracts, public.equipment,
  public.transmission, public.power, public.batteries, public.auxiliary, public.maintenance,
  public.mll_events, public.mll_bsc_summary, public.mll_analysis_summary, public.kpi_targets to authenticated;
grant select on public.audit_log to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Shared notifications for PC <-> Mobile
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text, notify_date text not null, notify_time text not null, content text,
  sound boolean not null default true, popup boolean not null default true, done boolean not null default false,
  auto_alert_key text, station_code text, sync_key text, created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
alter table if exists public.notifications add column if not exists sync_key text;
alter table if exists public.notifications add column if not exists station_code text;
alter table if exists public.notifications add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table if exists public.notifications add column if not exists updated_at timestamptz not null default now();
create index if not exists idx_notifications_date on public.notifications(notify_date, notify_time);
create unique index if not exists idx_notifications_sync_key on public.notifications(sync_key) where sync_key is not null;
alter table public.notifications enable row level security;
drop policy if exists notifications_select_authenticated on public.notifications;
drop policy if exists notifications_insert_authenticated on public.notifications;
drop policy if exists notifications_update_authenticated on public.notifications;
drop policy if exists notifications_delete_authenticated on public.notifications;
create policy notifications_select_authenticated on public.notifications for select to authenticated using (true);
create policy notifications_insert_authenticated on public.notifications for insert to authenticated with check (true);
create policy notifications_update_authenticated on public.notifications for update to authenticated using (true) with check (true);
create policy notifications_delete_authenticated on public.notifications for delete to authenticated using (true);

-- Explicit PostgREST privileges for the shared PC <-> Mobile notification stream.
grant select, insert, update, delete on public.notifications to authenticated;

-- V85.35: Repair the identity sequence after legacy/manual notification rows.
-- This prevents PostgREST inserts from reusing an existing notifications.id.
DO $$
DECLARE
  seq_name text;
  max_id bigint;
BEGIN
  seq_name := pg_get_serial_sequence('public.notifications', 'id');
  IF seq_name IS NOT NULL THEN
    SELECT COALESCE(MAX(id), 0) INTO max_id FROM public.notifications;
    PERFORM setval(seq_name, max_id + 1, false);
  END IF;
END $$;

