import 'package:flutter/material.dart';
import '../services/cloud_service.dart';
import 'operations_screen.dart';
class StationDetailScreen extends StatefulWidget{final String code;const StationDetailScreen({super.key,required this.code});@override State<StationDetailScreen> createState()=>_StationDetailScreenState();}
class _StationDetailScreenState extends State<StationDetailScreen>{final cloud=CloudService();Map<String,dynamic>? data;String? error;@override void initState(){super.initState();load();}Future<void> load()async{try{final x=await cloud.station(widget.code);if(mounted)setState(()=>data=x);}catch(e){if(mounted)setState(()=>error=e.toString());}}@override Widget build(BuildContext c){if(error!=null)return Scaffold(appBar:AppBar(title:Text(widget.code)),body:Center(child:Text(error!)));if(data==null)return const Scaffold(body:Center(child:CircularProgressIndicator()));final s=data!;final rel=Map<String,dynamic>.from(s['_related'] as Map);return Scaffold(appBar:AppBar(title:Text('${s['code']}')) ,body:ListView(padding:const EdgeInsets.all(16),children:[FilledButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const OperationsScreen())),icon:const Icon(Icons.build_circle),label:const Text('VẬN HÀNH TRẠM')),const SizedBox(height:10),_section('Thông tin trạm',{'Mã trạm':s['code'],'Tên trạm':s['name'],'Địa chỉ':s['address'],'UPE':s['upe'],'Mã điện kế':s['meter_code'],'Loại trụ':s['pole_type'],'Loại CSHT':s['csht_type'],'KTV':s['technician'],'Trạng thái':s['status']}),...rel.entries.map((e)=>_listSection(e.key,e.value as List<Map<String,dynamic>>))]));}}
Widget _section(String title,Map<String,dynamic> m)=>Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:10),...m.entries.where((e)=>e.value!=null&&e.value.toString().trim().isNotEmpty).map((e)=>Padding(padding:const EdgeInsets.symmetric(vertical:4),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(width:105,child:Text('${e.key}:',style:const TextStyle(fontWeight:FontWeight.w600))),Expanded(child:Text(e.value.toString()))]))) ])));
Widget _listSection(String title,List<Map<String,dynamic>> rows)=>ExpansionTile(title:Text('${title.toUpperCase()} (${rows.length})'),children:rows.take(20).map((r)=>ListTile(title:Text(_titleFor(r)),subtitle:Text(_summary(r)))).toList());
String _titleFor(Map<String,dynamic> r)=> (r['contract_no']??r['equipment_group']??r['work_type']??r['error_code']??r['link_type']??r['power_model']??r['battery_type']??r['category']??'Thông tin').toString();
String _summary(Map<String,dynamic> r){final skip={'id','created_at','updated_at'};return r.entries.where((e)=>!skip.contains(e.key)&&e.value!=null&&e.value.toString().isNotEmpty).take(4).map((e)=>'${e.key}: ${e.value}').join(' • ');}
